# -*- coding: utf-8 -*-
"""Registration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtO2qng1KYLe__n2Q_CagXMcwUVTEpKs
"""

# Registration - SORA-ATMAS Framework
# Registers the three domain agents and the governance authority to the blockchain

import json
import multichain

# --- Define the 4 core entities in SORA-ATMAS ---
weather_agent = {
    "Service name": "Weather Agent",
    "Authentication": "weather_auth_2025",
    "Authorization": ["Traffic Agent", "Safety Agent", "SORA"],
    "Access Control": ["1"],
    "Domain": "Meteorological monitoring & forecasting",
    "LLMs_used": ["GPT-4", "Grok-4", "DeepSeek-R1"],
    "Data_source": "OpenMeteo API"
}

traffic_agent = {
    "Service name": "Traffic Agent",
    "Authentication": "traffic_auth_2025",
    "Authorization": ["Weather Agent", "Safety Agent", "SORA"],
    "Access Control": ["2"],
    "Domain": "Vehicular density & congestion management",
    "LLMs_used": ["GPT-4", "Grok-4", "DeepSeek-R1"],
    "Data_source": "CCTV streams (YOLOv8)"
}

safety_agent = {
    "Service name": "Safety Agent",
    "Authentication": "safety_auth_2025",
    "Authorization": ["Weather Agent", "Traffic Agent", "SORA"],
    "Access Control": ["3"],
    "Domain": "Fire/Smoke hazard detection & response",
    "LLMs_used": ["GPT-4", "Grok-4", "DeepSeek-R1"],
    "Data_source": "CCTV streams (YOLO11)"
}

sora_gov = {
    "Service name": "SORA",
    "Authentication": "sora_gov_2025",
    "Authorization": ["Weather Agent", "Traffic Agent", "Safety Agent"],
    "Access Control": ["0"],
    "Role": "Governance Authority",
    "Function": "Adaptive trust-risk enforcement, policy validation, cross-domain coordination",
    "Blockchain": "SORA-Chain (global), Agentic-Chain (local)"
}

# --- Connect to Multichain ---
rpcuser = "multichainrpc"
rpcpassword = "2xYe2PpKbiCpuXfHVhJPDUiVuus3k1dinKfMriSCD6dx"
rpchost = "127.0.0.1"
rpcport = "9724"

try:
    mc = multichain.MultiChainClient(rpchost, rpcport, rpcuser, rpcpassword)
    print("Connected to MultiChain node successfully.")
except Exception as e:
    print(f"Error connecting to MultiChain: {e}")
    exit(1)

# --- Publish each entity to the stream ---
stream_name = "SORA_ATMAS_Registration"

try:
    mc.publish(stream_name, "Weather_Agent", {"json": weather_agent})
    mc.publish(stream_name, "Traffic_Agent", {"json": traffic_agent})
    mc.publish(stream_name, "Safety_Agent", {"json": safety_agent})
    mc.publish(stream_name, "SORA_Gov", {"json": sora_gov})
    print("All entities published to blockchain stream.")
except Exception as e:
    print(f"Error publishing to stream: {e}")
    exit(1)

# --- Save the last published entity locally ---
with open("sora_atmas_last_registration.json", "w") as file:
    json.dump(sora_gov, file, indent=4)
    print("Last entity (SORA) saved to 'sora_atmas_last_registration.json'.")

# --- Retrieve and display the last 4 stream items ---
try:
    all_items = mc.liststreamitems(stream_name)
    last_4_entities = all_items[-4:]  # Get last 4 registrations

    print("\n--- SORA-ATMAS Entity Registration Summary ---")
    print("Last 4 registered entities (from blockchain):")

    for idx, item in enumerate(last_4_entities, 1):
        entity_data = item['data']['json']
        print(f"{idx}. {entity_data['Service name']}")
        print(f"   Authentication: {entity_data['Authentication']}")
        print(f"   Domain/Role: {entity_data.get('Domain', entity_data.get('Role', 'N/A'))}")
        print(f"   Authorized to interact with: {', '.join(entity_data['Authorization'])}\n")

except Exception as e:
    print(f"Error retrieving stream items: {e}")